version: '2'

services:
    oracle_xe:
        image: quay.io/maksymbilenko/oracle-12c
        ports:
            - '49160:22'
            - '49161:1521'

    php:
        image: fpfis/httpd-php-oci:7.4
        working_dir: /var/www/html
        ports:
        - 8080:8080
        volumes:
        - .:/var/www/html # Non Mac users.
        # - nfsmount:/var/www/html # Mac Users with the nfsmount volume.
        environment:
            XDEBUG_CONFIG: "remote_enable=1 remote_host=10.254.254.254 remote_port=9000 idekey=PHPSTORM remote_autostart=1"
            PHP_IDE_CONFIG: "serverName=Docker"
